"""Add profile fields (bio, avatar, theme)

Revision ID: 47157a04c7b5
Revises: 98e5c401f4e2
Create Date: 2025-11-05 14:13:41.447783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47157a04c7b5'
down_revision = '98e5c401f4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('avatar')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
